### ISSUE TITLE
Analyze the possibility of using influxdb

### ISSUE THREAD

**Issue by ajcpereira** [ajcpereira/fj-collector#23]
This is a long term analysis to determine advantages of this move:

- once some use cases are running with graphite we can evaluate a move to influxdb

**Comment by machado-nuno** [comment]
Defined data structure, examples:

cpu,system="LAB",resource_type="linux_os",host="linux01" use=25,iowait=0,load1m=1.2
fs,system="LAB",resource_type="linux_os",host="linux01" mount="/dev/1",total=7935,used=1777

**Comment by machado-nuno** [comment]
Code was ported to use InfluxDB as the database. Results were positve, so InfluxDB will be used from this release forward.
